services:
  database:
    build:
      context: ./database
    container_name: devops_database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: devops_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - devops_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: devops_backend
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      APP_NAME: DevOps Student Management
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: password123
      DB_NAME: devops_db
      STUDENT_NAME: Phạm Nhân Tài
      STUDENT_ID: 2251220183
      CLASS: 22CT4
    depends_on:
      database:
        condition: service_healthy
    networks:
      - devops_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: devops_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - devops_network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  devops_network:
    driver: bridge
